name: CI - Run api and dashboard tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies for api
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
        pip install pytest

    - name: Run API tests
      run: |
        pytest api

    - name: Install dependencies for monitoring
      run: |
        pip install -r monitoring/requirements.txt

    - name: Run dashboard tests
      run: |
        pytest monitoring
